// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarousselController from "./caroussel_controller"
application.register("caroussel", CarousselController)

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
